name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Archive files
      run: |
        zip -r LiteLoaderQQNT-image-search.zip . -x "*.git*" -x "*.github*"

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: Release ${{ github.event.after }}
        draft: false
        prerelease: false
        artifacts: LiteLoaderQQNT-image-search.zip
